# Generated by Django 5.1 on 2025-10-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del usuario', max_length=255)),
                ('apellido', models.CharField(blank=True, help_text='Apellido del usuario', max_length=255, null=True)),
                ('email', models.EmailField(help_text='Dirección de correo electrónico (única)', max_length=254, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha en que el usuario se registró')),
                ('tipo_membresia', models.CharField(choices=[('Basica', 'Básica'), ('Estandar', 'Estándar'), ('Premium', 'Premium')], default='Basica', help_text='Tipo de membresía del usuario', max_length=100)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['fecha_registro', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la suscripción')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin de la suscripción (si aplica)', null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Tarjeta', 'Tarjeta de Crédito/Débito'), ('PayPal', 'PayPal'), ('Transferencia', 'Transferencia Bancaria')], help_text='Método de pago utilizado', max_length=100, null=True)),
                ('costo_mensual', models.DecimalField(decimal_places=2, help_text='Costo mensual de la suscripción', max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='app_usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
