# Generated by Django 5.1 on 2025-10-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='fotos_perfil/'),
        ),
    ]
